.TH vkeybd 1 "January 1, 2000"
.LO 1
.SH NAME
vkeybd \- virtual keyboard on X

.SH SYNOPSIS
.B vkeybd
[\-options]

.SH DESCRIPTION
.B vkeybd
is a virtual keyboard for AWE/OSS, MIDI/OSS and ALSA drivers.
It's a simple fake of a MIDI keyboard on X-windows system.
Enjoy a music with your mouse and
.I computer
keyboard :-)

.SH OPTIONS
.SS "Common Options"
.TP
.B \--device mode
Use the specified mode for output device.
The argument are
.B awe,
.B midi
or
.B alsa,
for AWE/OSS, MIDI/OSS and ALSA devices, respectively.
Default is
.B alsa.
.TP	
.B \--keymap file
Use the specified file as keymap file (see section "KEY ASSIGNMENT").
.TP
.B \--preset file
Use the specified file as preset list file (see section "PRESET LIST FILE").
.TP
.B \--channel num
Specify the channel to be played for normal instruments.
Valid only for MIDI and ALSA devices. Default is 0.
.TP
.B \--drum num
Specify the channel to be played for drum instruments.
Valid only for MIDI and ALSA devices. Default is 9.

.SS "ALSA Device Option"
.TP
.B \--addr destination
Set ALSA client and port numbers to be connected.
If argument begins with 's' or 'S', the port is opened as subscription
port, and events are sent to all connected subscribers.  The port can be
connected to other ports via
.B aconnect(1).
Otherwise,
.B vkeybd
connects directly to the specified port.  The argument must be
a form like client:port or client.port, where client and port are index
numbers listed in
.B /proc/asound/seq/clients.
Default is 's'.

.SS "OSS Sequencer Device Options"
.TP
.B \--seqdev file
Specify the device file path for sequencer access.
As default
.B /dev/sequencer
is used.
.TP
.B \--seqidx num
Specify the synth device index for AWE32/64 WaveTable.
If negative value is given, the device is auto-probed.
Default value is -1.

.SS "MIDI Device Option"
.TP
.B \--mididev num
Speicfy the file path of MIDI device.
Default value is /dev/midi.

.SH "BUTTONS"
The lowest value of visible three octave note keys is shown in the
.I KEY
scale bar (as default 48, #C4).  You can play a tone by clicking
the mouse button on the virtual keyboard.

Each visible key is mapped on your computer keyboard from 'z' to '\\'.
To use the computer keyboard, you should turn off auto repeat on your
X display via
.B xset(1):
.IP "" 4
% xset -r
.PP
The
.I Power
button is used to release the sequencer device from
virtual keyboard.  On OSS system, only one application is allowed to
access sequencer device.  Thus, if one wants to play another program
event using another device, he needs to disconnect
.B vkeybd
once.
On ALSA or OSS emulation on ALSA, you don't have to switch
.B vkeybd
off,
since multiple access is allowed.
.PP
The
.I VEL
scale bar is used to change the velocity of the sound.
.PP
The right button from
.I Power
is a controller selection button.
When this button is pressed, a pull-down menu appears, and you can
select the control event to be changed by the scale bar in the right
side of this button.  The
.I Reset
item is used to reset all the
controller values to the default ones.
.PP
The
.I Chorus
and
.I Reverb
buttons are menu buttons to choose the
arbitrary chorus and reverb modes, respectively.  It is valid only on
AWE device mode.
.PP
The scale bar in the right side of these buttons represents a virtual
pitch wheel.
.I ClrPitch
button is used to reset the wheel position to normal.
.PP
The
.I Program
button is used to enable/disable selection of playing
instrument.  The shown presets are read from preset list file.

.SH "KEY ASSIGNMENT"
The key assignment can be changed by a keymap file.  Each line of keymap
file consists of key symbol and midi note number offset separated by
space.  The key symbol is the
.B X(1)
key symbol for assigned key, and note
offset is the shifted note number from note key of beginning of
keyboard, which is changed by
.I KEY
scalebar.  For example, if a line
contains "a 8" and the lowest note is 48, then MIDI note 56 will be
played by pressing the computer key "a".  The following files are
searched as keymap file:
.B ~/vkeybd.key,
.B ~/.vkeybd.key
and
.B $vkblib/vkeybd.key
where
.B $vkblib
is the installed path of vkeybd data.
The default path of vkeybd data is
.B /usr/local/share/vkeybd.
For other files, you need to specify the path
by
.B \--keymap
command line option.

.SH "PRESET LIST FILE"
The preset list file is used to describe the list of MIDI preset
names.  If the command line option is omitted, the default preset list
file
.B ~/vkeybd.list,
.B ~/.vkeybd.list
and
.B $vkblib/vkeybd.list
are searched sequentially.  The preset list will appear when
.I Program
toggle button is on, and you can select a tone to be played from the list.
.PP
The preset list file can be converted from
.B SoundFont(tm)
file via
.B sftovkb(1)
utility.  For example,
.IP "" 4
% sftovkb synthgm.sbk > vkeybd.list
.PP

.SH "SEE ALSO"
sftovkb(1), X(1), xset(1), aconnect(1)

.SH AUTHOR
Takashi Iwai <tiwai@suse.de>
